dataset:
    name: utkface
    config:
        filter_gender: null
    val_indices: configs/utkface-all_val_indices.npy

regressor:
    source: models/weights/utkface/resnet50-GN_model_29700.pt
    arch_type: cnn
    config:
        backbone: resnet50-GN
        pretrained: false
        in_channels: 3

calculator:
    compile_model: null

dataloader:
    batch_size: 256