dataset:
    name: utkface
    config:
        filter_gender: null
    val_indices: configs/utkface-all_val_indices.npy

regressor:
    source: models/weights/utkface/vit-b-16-224-LN_model_29700.pt
    arch_type: vit
    config:
        backbone: vit-b-16-224-LN
        pretrained: false
        in_channels: 3

calculator:
    compile_model: null

dataloader:
    batch_size: 256